# Sources
SDIR = source
SRCS = game.cpp engine.cpp interface.cpp map.cpp objects.cpp thing.cpp tile.cpp unit.cpp
# Objects
ODIR = build/
OBJS = $(SOURCES:.cpp=.o)
# Executable
EXE = 2dpcrpg
# Compiler
CC = g++
# Debug
DEBUG = -g
# Flags
CFLAGS = -Wall -c $(DEBUG)
LFLAGS = -Wall $(DEBUG)
# Libraries
LIBS = -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer

all: $(SRCS) $(EXE)

$(EXE) : $(OBJS)
	$(CC) $(LFLAGS) $(OBJS) -o $@ $(LIBS)

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@
	
depend:
	makedepend -- $(CFLAGS) -- $(SRCS)

clean:
	rm -rf *o $(EXE)
